FROM maven:3.6.1-ibmjava-8

# Set the working directory to /
WORKDIR /

# Copy the current directory contents into the container at /
COPY . /

RUN apt-get install git -y && git clone https://solitarysp:Chicanem1234@github.com/solitarysp/WebXBE.git
WORKDIR /WebXBE
RUN mvn package
VOLUME ["/usr/share/maven","/root/.m2"]
FROM openjdk:8

WORKDIR /
# coppy từ image 0 với url thư mục  WebXBE/target/ đến / của container này
COPY --from=0 /WebXBE/target/ .
CMD ["java","-jar","BEX-1.0-SNAPSHOT.jar"]
